"""Model store outbound port."""

from typing import Protocol

import lightgbm as lgb


class ModelStore(Protocol):
    def save(self, run_id: str, booster: lgb.Booster, metrics: dict) -> str: ...
    def load(self, run_id: str) -> lgb.Booster: ...
    def set_latest(self, run_id: str) -> None: ...
    def get_latest_run_id(self) -> str: ...
