# Cloud Build config for the training-job image.
# Used by `make deploy-training-job-local` and
# `.github/workflows/deploy-training-job.yml`. See
# infra/run/services/search_api/cloudbuild.yaml for
# rationale.

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=infra/run/jobs/training/Dockerfile
      - --tag=${_URI}
      - .
images:
  - ${_URI}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _URI: ""
